version: '3.7'
services:
  jobmanager:
    image: flink:1.20.0
    hostname: jobmanager
    container_name: flink_jobmanager
    ports:
      - "8081:8081"  # Flink Web UI
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        jobmanager.memory.process.size: 1024m 
    command: jobmanager

  taskmanager:
    image: flink:1.20.0
    hostname: taskmanager
    container_name: flink_taskmanager
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        taskmanager.memory.process.size: 1024m
    command: taskmanager

  sql-client:
    image: custom-flink-with-connectors:1.15.0
    container_name: flink_sql_client
    depends_on:
      - jobmanager
      - taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.rpc.port: 6123  
        parallelism.default: 1
    entrypoint: ["bin/sql-client.sh"]

  zookeeper:
    image: zookeeper:latest
    container_name: pinot-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: pinot-zookeeper:2181/kafka
      KAFKA_BROKER_ID: 0
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.16.5.49:9092 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rajat_123
      MYSQL_DATABASE: my_db
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_pw
    ports:
      - "3307:3306"